id: P851851A1
initial_creation_type: input
source_metadata:
  title: Sickness and Healing
  language: en
  description: 'Lotsawa House presents the following texts as part of our Sickness
    and Healing Series:'
  volume:
    993a32ee9f6a4e94b0bc98ef6e017262:
      title: Three Ways of Bringing Sickness onto the Path
      parent: Advice
    a2651a769d9e4aac9f6777a9563c3c5d:
      title: How to Transform Sickness and Other Circumstances
      parent: Advice
    557dca6c63654c23bc6691f8b778f824:
      title: The Universal Medicine for Healing All Ills
      parent: Advice
    c9b28c6bb4d8490e9ca0428a4e80785b:
      title: The Mantra Collection that Incinerates All the Diseases of this Kaliyuga
      parent: Mantras
    a5f261ba215348e7a755a4fa76a11bba:
      title: Wrathful Guru Mantra Visualization
      parent: Mantras
    a68e72eeafe2485794f2058bd50057cd:
      title: Dhāraṇī of Goddess Parṇaśavarī
      parent: Practices
    f4f70c73d88a49ca8c2eeed04497a241:
      title: Daily Practice of Guru Rinpoche, Buddha of Medicine
      parent: Practices
    3976606cf0824c79b32943dc1644ac6f:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Practices
    959f0c694bfa424e82d5fcaac720140a:
      title: Daily Practice of Dorje Gotrab
      parent: Practices
    92d670c291fa4085a05d303bd61aad2d:
      title: 'Fast Track to Happiness and Peace: A Very Brief Meditation and Recitation
        of the Medicine Buddha'
      parent: Practices
    a0869b814d154bf997cfd715bfe50cd3:
      title: Sādhana of Bhaiṣajya Guru (Medicine Buddha)
      parent: Practices
    5318ca1e6b544528a18a2a0d8b215ab2:
      title: 'Zabchema: Profound Cure, The Practice of Bhaiṣajya-Guru, Lord of Physicians'
      parent: Practices
    56ea82f71d4b468eaff280ab1fbc0cd1:
      title: Acala Sādhana
      parent: Practices
    418b10a5977d42329c9197f94b46aad0:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Practices
    514755ec8e844b8eb9f37ac97507579e:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Prayers
created_at: '2022-03-01T05:47:13.658733'
last_modified_at: '2022-03-01T05:47:13.658740'
